import React from "react";
import Head from "next/head";
import styles from "../styles/Layout.module.css";
import { Menu } from "./Menu";
import ShoppingCart from "./ShoppingCart";

const Layout = ({ children, title }) => {
  return (
    <div>
      <Head>
        {/*  <title>Github Mercar {title ? `| ${title}` : " "}</title> */}
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Menu />
      <div className={styles.container}>{children}</div>

      <ShoppingCart />
    </div>
  );
};

export default Layout;
